# encoding: utf-8
require 'bundler'
require 'rubygems'
require 'rake'

task :strange_migrate do
      source = File.join(File.dirname(__FILE__),  'db')
      destination = File.join(Rails.root, 'db')
      Spree::FileUtilz.mirror_files(source, destination)
end

namespace :gem do
  desc "run gem install for all gems"
  task :install do
    source = File.join(File.dirname(__FILE__),  'db')
      destination = File.join(Rails.root, 'db')
      Spree::FileUtilz.mirror_files(source, destination)
  end
end